import Head from 'next/head';
import Header from '../components/header';
import Banner from '../components/banner';
import Styleguide from '../components/styleguide';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Banner />
        <Styleguide />
      </main>
    </div>
  );
}
